version: "3"

services:

  mysql:
    image: mysql
    networks:
      - interna
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=wordpress
    volumes:
      - /docker/storage/wp/database:/var/lib/mysql

  wordpress:
    image: wordpress
    ports:
      - 81:80
    networks:
      - interna
    volumes:
          - /docker/storage/wp/uploads:/var/www/html/wp-content/uploads
    depends_on:
      - mysql
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_PASSWORD=12345
      - WORDPRESS_DB_USER=root

networks:
    interna: