version: "3"

services:
  db:
    image: mysql
    volumes:
     - /docker-storage/wp:/lib/mysql/data
    networks:
      - wp-network
  application:
    image: wordpress
    volumes:
      - /docker-storage/wp:/var/www/html/wp-content/uploads
    depends:
      - db
    networks:
      - wp-network