version: "3"

services:

  mysql:
    image: mysql
    volumes:
      - type: volume
          source: /docker/storage/wp/database
          target: /var/lib/mysql
    networks:
      - interna
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=wordpress

  wordpress:
    image: wordpress
    ports:
      - 81:80
    volumes:
      - type: volume
        source: /docker/storage/wp/uploads
        target: /var/www/html/wp-content/uploads
    networks:
      - interna
    depends_on:
      - mysql
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_PASSWORD=12345
      - WORDPRESS_DB_USER=root

networks:
    interna: