version: "3"

services:

  mysql:
    image: mysql
    networks:
      - interna
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=wordpress

  wordpress:
    image: wordpress
    ports:
      - 81:80
    networks:
      - interna
    depends_on:
      - mysql
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_PASSWORD=12345
      - WORDPRESS_DB_USER=root

networks:
    interna: